server:
  port: 51803
spring:
  application:
    name: leadnews-wemedia
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_article?useSSL=false
    username: root
    password: 12345678
#    url: jdbc:mysql://localhost:3306/leadnews_user?useSSL=false
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.jdbc.Driver
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.common.user.entity
minio:
  accessKey: minio
  secretKey: minio123
  bucket: leadnews
  endpoint: http://localhost:9001
  readPath: http://localhost:9001
aliyun:
  accessKeyId: LTAI5t7kJEvxvqpAQ5bgqj4y
  secret: lzhbrjQDphb26l8Fy1ttygULYkwSpp
  #aliyun.scenes=porn,terrorism,ad,qrcode,live,logo
  scenes: terrorism
tess4j:
  data-path: /Users/Project/myself/project/tess4j/tessdata
  language: chi_sim
#feign:
#  # 开启feign对hystrix熔断降级的支持
#  hystrix:
#    enabled: true
#  # 修改调用超时时间
#  client:
#    config:
#      default:
#        connectTimeout: 2000
#        readTimeout: 2000